# These are supported funding model platforms

github: jdnichollsc
patreon: proyecto26
open_collective: proyecto26
ko_fi: proyecto26
tidelift: # npm/nativescript-inappbrowser
custom: paypal.me/jdnichollsc
